name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # 添加环境变量
      - name: Set environment variables
        shell: bash
        run: |
          echo "CI=false" >> $GITHUB_ENV

      # 安装依赖
      - name: Install dependencies
        run: |
          npm install
          npm install -g cross-env

      # 修改构建命令
      - name: Build React app
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf build
          npm install
          npm run build

      # 执行electron打包
      - name: Build electron app
        run: |
          npm run electron-pack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb

      - name: Create Release
        if: startsWith(matrix.os, 'windows')
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}